### ISSUE TITLE
Network error: [Errno 111] - Cannot interact with CoAP server outside a Docker Container

### ISSUE THREAD

**Issue by J0hn3ch** [chrysn/aiocoap#349]
Hi everyone,

I'm trying to build a CoAP server project, using aiocoap and Docker containers.

I'm using the Docker Compose file to manage containers in the project and a Dockerfile to build the images for the container. In this case I use a Docker image of Ubuntu to build the custom image with CoAP Server (installing python, requirements and running server.py from the aiocoap tutorial).

**compose.yml**
``` 
# CoAP Server Ubuntu 20.04
services:
  coap_server-2:
    container_name: ubuntu-coap-server
    build:
      context: coap-server-2
      no_cache: false
    volumes:
      - ./coap-server-2:/app/
    restart: always
    network_mode: host
    ports:
      - 80:80/udp
      - 5683:5683/udp
```
### Testing the server with aiocoap-client

**The problem:** Request outside the container, with WSL Ubuntu
```
$ aiocoap-client -m GET coap://127.0.0.1:5683/.well-known/core
Network error: [Errno 111] received through errqueue
```
In my case, I need to interact outside the container, because all the compose file will be executed in a Raspberry, so I need to send coap request from a Client (e.g. ESP32) to a CoAP Server (Raspberry Pi). 

**How can I solve this issue?**

**Working example:** Request inside the container
After open the bash of the container with the command `docker exec -it coap-server bash`
```
coapuser@docker-desktop:/app$ aiocoap-client -m GET coap://127.0.0.1:5683/.well-known/core
Response arrived from different address; base URI is coap://127.0.0.1/.well-known/core
</.well-known/core>;ct="40",</>,</time>;obs,</other/block>,</other/separate>;title="A large resource",</whoami>,<https://christian.amsuess.com/tools/aiocoap/#version-0.4.7>;rel="impl-info" 
```

### aiocoap.cli.defaults: output
```coapuser@docker-desktop:/app$ python3 -m aiocoap.cli.defaults
Python version: 3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0]
aiocoap version: 0.4.7
Modules missing for subsystems:
    dtls: missing DTLSSocket
    oscore: missing cbor2, cryptography, filelock, ge25519
    linkheader: everything there
    prettyprint: missing cbor2, termcolor, pygments
Python platform: linux
Default server transports:  tcpserver:tcpclient:tlsserver:tlsclient:udp6
Selected server transports: tcpserver:tcpclient:tlsserver:tlsclient:udp6
Default client transports:  tcpclient:tlsclient:udp6
Selected client transports: tcpclient:tlsclient:udp6
SO_REUSEPORT available (default, selected): True, True```
